In [1]:
#NAME Tanvi Shelke
#roll no:58

In [43]:
import pandas as pd
import numpy as np

In [3]:
import os

In [4]:
os.getcwd()

'C:\\Users\\USER'

In [24]:
os.chdir('C:\\tanvi\\USER\\Desktop')

In [25]:
data=pd.read_csv("Salary_Data.csv")

In [26]:
data.head(34)

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [27]:
data.tail()

    YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [28]:
data.shape

(30, 2)

In [29]:
data.size

60

In [30]:
data.ndim

2

In [31]:
data.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes

In [33]:
data.isnull()

    YearsExperience  Salary
0             False   False
1             False   False
2             False   False
3             False   False
4             False   False
5             False   False
6             False   False
7             False   False
8             False   False
9             False   False
10            False   False
11            False   False
12            False   False
13            False   False
14            False   False
15            False   False
16            False   False
17            False   False
18            False   False
19            False   False
20            False   False
21            False   False
22            False   False
23            False   False
24            False   False
25            False   False
26            False   False
27            False   False
28            False   False
29            False   False

In [34]:
data.isna().any()

YearsExperience    False
Salary             False
dtype: bool

In [35]:
data.isna().sum()

YearsExperience    0
Salary             0
dtype: int64

In [37]:
x=data.drop("Salary",axis=1)

In [38]:
x.head()

   YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [40]:
y = data.Salary

In [41]:
y.head()

0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
Name: Salary, dtype: float64

In [42]:
from sklearn.model_selection import train_test_split

In [46]:
x_train,x_test,y_train,y_test= train_test_split(
    x, y, test_size=0.30, random_state=0)

In [48]:
print(x_train.shape)

(21, 1)

In [49]:
print(x_test.shape)

(9, 1)

In [50]:
from sklearn.linear_model import LinearRegression
LR= LinearRegression()
LR.fit(x_train,y_train)

LinearRegression()

In [51]:
#coefficeant (slope)to m
m = LR.coef_

In [53]:
print("coefficient :",m)

coefficient : [9360.26128619]

In [55]:
c = LR.intercept_

In [56]:
print("intercept :",c)

intercept : 26777.391341197632